# Generated by Django 3.2 on 2021-04-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_publicacion_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='snippet',
            field=models.CharField(default='Da click en el enlace para leer la historia completa', max_length=255),
        ),
    ]
